services:
  mysql:
    build: ./database
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ferremas_db
      MYSQL_USER: ferremas_usr
      MYSQL_PASSWORD: contrasenasegura123
      MYSQL_ROOT_PASSWORD: contrasenasegura123root
    command: --general-log=1 --general-log-file=/var/lib/mysql/general.log
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:
